name: MajZip
on:
  push:
    branches:
      - main
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: foundry-vtt-module-conan-2d20-fr.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: yannrousseaux
      
      - name: Create zip folder
        run: zip -r -q foundry-vtt-module-conan-2d20-fr.zip foundry-vtt-module-conan-2d20-fr

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: yannrousseaux
        with:
          add: '["foundry-vtt-module-conan-2d20-fr.zip"]'
          message: 'Mise à jour du zip'
          push: true

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: yannrousseaux