name: MaJ Zip
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create zip folder
        run: zip -r -q foundry-vtt-module-conan-2d20-fr.zip folder

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: '["foundry-vtt-module-conan-2d20-fr.zip"]'
          message: 'My commit message'
          push: true